= MidiJam Decompilation

This is a work-in-progress decompilation of http://gamesbyscott.com/midijam.htm[MidiJam] (Version 1.12).

== Building

This project uses https://cmake.org[CMake] as the build system.

=== Prerequisites

==== Software

You will need the following software installed:

* Microsoft Visual C++ 8.0 or higher. More testing is needed to determine which version of MSVC likely was used in the original compilation.
* https://archive.org/details/dxsdk_oct2004[Microsoft DirectX 9.0 SDK (October 2004)]. Set the `DXSDK_DIR` environment variable to the installation location (usually done automatically by the installer).

==== Resources

Load these files into the `res` directory before building:

* `MidiJam.HWF`, which can be sourced from an official download of the http://gamesbyscott.com/midijam.zip[MidiJam package]
* `HWF.cfg`, which can be generated by running `Config.exe` from the MidiJam package
* Said `Config.exe`, in case MidiJam tries to launch it

=== Compiling

Instructions coming soon!

=== Additional information

You can verify you have the correct version of MidiJam by using the following checksum:

* MidiJam.exe `md5: ddf8d26d15f33110ac19158cf260f2e3`